# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HouseAlarm' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HouseAlarm
pod 'MBProgressHUD'
pod 'AFOnoResponseSerializer'
pod 'Masonry'
pod 'CWLateralSlide', '~> 1.5.5'
pod 'TSMessages'
pod 'MJRefresh'
pod 'YYKit'
pod 'MMPlaceHolder'

end
